# Generated by Django 2.1.5 on 2020-06-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_userprofile_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerorder',
            name='userid',
        ),
    ]
