# Generated by Django 2.0.2 on 2020-06-12 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoppcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prodcartid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Products')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shoppcart',
            unique_together={('prodcartid', 'buyerid')},
        ),
    ]
